#!/usr/bin/env bash

# Fixture suite for scripts/check-message-catalog.sh. Every case builds a
# throwaway git repository and drives the check with a fake generator command
# (`GENERATOR_CMD`), so the real `npm run extract-messages` — slow, and
# dependent on the whole dependency tree — never runs. Seconds, offline, no
# node_modules.
#
# The cases mirror the incident this gate exists for (#72): the generator and
# the committed catalog diverging in either direction (a tracked file rewritten,
# or a new file appearing) must fail the check, while a generator that
# reproduces the committed bytes exactly must pass even though it rewrote the
# file.

set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
repo_root=$(cd -- "$script_dir/.." && pwd -P)
check_script="$repo_root/scripts/check-message-catalog.sh"

fixture_root=$(mktemp -d "${TMPDIR:-/tmp}/message-catalog-fixtures.XXXXXX")
cleanup() {
  local status=$?
  if (( status == 0 )); then
    rm -rf -- "$fixture_root"
  else
    echo "message-catalog fixtures: leaving fixture root for inspection: $fixture_root" >&2
  fi
}
trap cleanup EXIT

failure_output="$fixture_root/failure-output.txt"

# `expected_status` is either an exact exit status or the literal `nonzero`.
expect_failure() {
  local expected_status=$1
  local expected_message=$2
  shift 2
  local status
  set +e
  "$@" >"$failure_output" 2>&1
  status=$?
  set -e
  if [[ $expected_status == nonzero ]]; then
    if [[ $status -eq 0 ]]; then
      echo "expected a non-zero exit status, got 0" >&2
      sed -n '1,120p' "$failure_output" >&2
      exit 1
    fi
  elif [[ $status -ne $expected_status ]]; then
    echo "expected status $expected_status, got $status" >&2
    sed -n '1,120p' "$failure_output" >&2
    exit 1
  fi
  if ! grep -Fq -- "$expected_message" "$failure_output"; then
    echo "expected failure message not found: $expected_message" >&2
    sed -n '1,120p' "$failure_output" >&2
    exit 1
  fi
}

assert_output_contains() {
  local expected=$1
  if ! grep -Fq -- "$expected" "$failure_output"; then
    echo "expected output to contain: $expected" >&2
    sed -n '1,120p' "$failure_output" >&2
    exit 1
  fi
}

# Builds a fixture repository with a committed messages/ catalog. The catalog
# files carry no trailing newline, matching what scripts/extract-messages.mjs
# emits — the exact byte the hand-edit in commit 30c2b3b4 added.
make_fixture_repo() {
  local name=$1
  local dir="$fixture_root/$name"
  mkdir -p -- "$dir/messages/en-US"
  printf '{\n  "a": "one"\n}' >"$dir/messages/en-US/primary.json"
  printf '{\n  "b": "two"\n}' >"$dir/messages/en-US/secondary.json"
  git -C "$dir" init -q
  git -C "$dir" config user.email fixture@example.com
  git -C "$dir" config user.name fixture
  git -C "$dir" config commit.gpgsign false
  git -C "$dir" add -A
  git -C "$dir" commit -qm 'fixture catalog'
  printf '%s\n' "$dir"
}

# Runs the check against a fixture repo with the given generator command.
run_check() {
  local repo=$1
  local generator=$2
  CATALOG_REPO_ROOT=$repo GENERATOR_CMD=$generator "$check_script"
}

generator_dir="$fixture_root/generators"
mkdir -p -- "$generator_dir"

# Rewrites a tracked catalog file (case B).
cat >"$generator_dir/rewrite-tracked.sh" <<'GEN'
#!/usr/bin/env bash
printf '{\n  "a": "changed"\n}' > messages/en-US/primary.json
GEN

# Creates a new, untracked catalog file (case C).
cat >"$generator_dir/create-untracked.sh" <<'GEN'
#!/usr/bin/env bash
printf '{\n  "c": "three"\n}' > messages/en-US/extra.json
GEN

# Rewrites a tracked catalog file with byte-identical content (case D).
cat >"$generator_dir/rewrite-identical.sh" <<'GEN'
#!/usr/bin/env bash
printf '{\n  "a": "one"\n}' > messages/en-US/primary.json
GEN

chmod +x "$generator_dir/rewrite-tracked.sh" \
  "$generator_dir/create-untracked.sh" \
  "$generator_dir/rewrite-identical.sh"

# --- case A: clean catalog, no-op generator ----------------------------------

clean_repo=$(make_fixture_repo clean)
run_check "$clean_repo" true >/dev/null

# --- case B: generator rewrites a tracked file -------------------------------

rewrite_repo=$(make_fixture_repo rewrite-tracked)
expect_failure 1 'diverges' run_check "$rewrite_repo" "$generator_dir/rewrite-tracked.sh"
assert_output_contains 'messages/en-US/primary.json'
assert_output_contains '+  "a": "changed"'

# --- case C: generator creates an untracked file -----------------------------

untracked_repo=$(make_fixture_repo create-untracked)
expect_failure 1 'diverges' run_check "$untracked_repo" "$generator_dir/create-untracked.sh"
assert_output_contains 'messages/en-US/extra.json'

# --- case D: generator rewrites a tracked file identically -------------------

# The regenerated bytes match the committed bytes, so the catalog has not
# diverged: the check must compare content, not merely notice that the
# generator ran or that the file's mtime moved.
identical_repo=$(make_fixture_repo rewrite-identical)
run_check "$identical_repo" "$generator_dir/rewrite-identical.sh" >/dev/null

echo 'check-message-catalog fixtures: PASS'
